Include CopyButton for both token and XCH values of generate offers to enhance user experience
Yakuhito/tibet-ui pull request #20
Opened 2023-11-17 04:14 UTC by johnathon-b

**User Story:**
As a user creating manual offer files, I want the ability to quickly and easily copy token and XCH values, so that I can streamline the process of generating offers and reduce the risk of errors.

**Description:**
In the current process of creating manual offer files, users have to manually select and copy the token, XCH and fee values, which can be time-consuming and prone to errors. To enhance the user experience and increase efficiency, we will utilize 'CopyButton' within the UI for token, XCH and fee values in the generate offers component.

2023-11-17 04:49 UTC, Yakuhito requested changes
Hey there! Thanks for your contribution - although it's easier to interact with the Chia wallet through WalletConnect, I think that the 'paste offer' functionality gives users more flexibility (e.g., they can use a completely different wallet - it only needs to support offers!). I left some comments about things that will need to be resolved before merging :)

2023-11-17 04:49 UTC, Yakuhito commented on src/components/trade_components/GenerateOffer.tsx
> +                        <span><CopyButton copyText={fee}>{fee} {process.env.NEXT_PUBLIC_XCH}</CopyButton></span>
Why are the `<span>` classes removed here?

2023-11-17 04:49 UTC, Yakuhito commented on src/components/trade_components/GenerateOffer.tsx
> +                            <CopyButton copyText={amountWithFee(e)}>{amountWithFee(e)} {process.env.NEXT_PUBLIC_XCH === "TXCH" && e[0].name === "Chia" ? "Testnet Chia" : e[0].name === "Pair Liquidity
copyText should be a string, `amountWithFee(e)` is a number (that's why Vercel builds are failing - you can try running `npm build' locally to see the error)

2023-11-17 04:49 UTC, Yakuhito commented on src/components/trade_components/GenerateOffer.tsx
> +                        <span><CopyButton copyText={fee}>{fee} {process.env.NEXT_PUBLIC_XCH}</CopyButton></span>
also, `fee` is a number (needs to be converted to string)

2023-11-17 11:47 UTC, JonathanLangton1 commented
Hi, my thoughts on this are that instead of another button, the user should have the ability to click directly on the value (text) itself to copy. You can probably use the CopyButton component with additional class names to remove all styling.

Happy to make these changes if you'd like me to.

2023-11-17 13:30 UTC, johnathon-b commented
I can change the styling today and push a commit. Should we still include the copy symbol so the user is aware of the functionality or make it something discoverable. 🤔

2023-11-17 14:22 UTC, JonathanLangton1 commented
> I can change the styling today and push a commit. Should we still include the copy symbol so the user is aware of the functionality or make it something discoverable. 🤔

I was thinking, for now, if you hover over the value text, just make the opacity of it 80% with cursor: pointer

2023-12-23 22:40 UTC, JonathanLangton1 commented
Should be good to go now 🙂

2023-12-24 14:03 UTC, merged